services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: music_room_backend
    env_file:
      - ./backend/.env
    ports:
      - "3003:3000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: music_room_db
    env_file:
      - ./backend/.env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: music_room_cache
    ports:
      - "${REDIS_PORT:-6379}:6379"

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: music_room_pgadmin
    env_file:
      - ./backend/.env
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./backend/pgadmin/servers.json:/pgadmin4/servers.json:ro

volumes:
  postgres_data:
  pgadmin_data:
