services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: music_room_backend
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    ports:
      - "${BACKEND_PORT:-3000}:3000"
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    container_name: music_room_frontend
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    restart: unless-stopped
    depends_on:
      - backend
